sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rwdumee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rwdumee/docker-react npm run test